<#
.SYNOPSIS
    Enforces the Arrow parsing reliability gate for this connector.

.DESCRIPTION
    Runs a fixed validation sequence to reduce regressions in Arrow parsing:
    0) Live endpoint shape assertion — probes the configured tenant's
       executeDaxQueries endpoint and confirms it still returns Apache
       Arrow IPC bytes. If PBI ever silently downgrades the response to
       JSON, the parity tests below would degrade to JSON-vs-JSON
       validation; this step catches that.
    1) Focused DateDim parity tests (compile enabled) — exercises the
       Arrow IPC code path of ExecuteDaxQueries against ExecuteQuery on
       the live tenant cell-by-cell.
    2) Connector proof tests
    3) Arrow helper unit tests (isolated Arrow sub-parser tests)
    4) Arrow static fixture parser tests — exercises the Arrow IPC code path
       end-to-end against deterministic pyarrow-generated byte fixtures.
       This is the credential-free Arrow-path validation step; see
       PBIRESTAPIComm.tests.arrow.staticfixture.query.pq.
    5) Multi-iteration DateDim soak run

.PARAMETER SoakIterations
    Number of soak iterations to run. Default is 5.

.EXAMPLE
    .\CI\Scripts\Run-ArrowParsingGate.ps1

.EXAMPLE
    .\CI\Scripts\Run-ArrowParsingGate.ps1 -SoakIterations 10
#>
param(
    [ValidateRange(1, 100)]
    [int]$SoakIterations = 5
)

$ErrorActionPreference = "Stop"

$RepoRoot = (Resolve-Path (Join-Path $PSScriptRoot "..\.." )).Path
$RunPQTests = Join-Path $RepoRoot "CI\Scripts\Run-PQTests.ps1"
$RunSoak = Join-Path $RepoRoot "CI\Scripts\Run-DateDimArrowSoak.ps1"
$AssertArrowShape = Join-Path $RepoRoot "CI\Scripts\Assert-ArrowResponseShape.ps1"
$ArtifactsDir = Join-Path $RepoRoot "artifacts\arrow-gate"

if(-not (Test-Path -Path $RunPQTests)){
    Write-Error "Missing script: $RunPQTests"
    exit 1
}

if(-not (Test-Path -Path $RunSoak)){
    Write-Error "Missing script: $RunSoak"
    exit 1
}

if(-not (Test-Path -Path $AssertArrowShape)){
    Write-Error "Missing script: $AssertArrowShape"
    exit 1
}

if(-not (Test-Path -Path $ArtifactsDir)){
    New-Item -Path $ArtifactsDir -ItemType Directory | Out-Null
}

$stamp = Get-Date -Format "yyyyMMdd-HHmmss"
$summaryPath = Join-Path $ArtifactsDir ("arrow-gate-{0}.md" -f $stamp)
$script:steps = @()

function Invoke-GateStep {
    param(
        [Parameter(Mandatory = $true)]
        [string]$Name,
        [Parameter(Mandatory = $true)]
        [scriptblock]$Command,
        [Parameter(Mandatory = $true)]
        [string]$LogPath,
        [string[]]$SuccessMarkers = @("All split test files passed")
    )

    Write-Host ""
    Write-Host "==> $Name"

    $output = & $Command *>&1
    $output | Out-File -FilePath $LogPath -Encoding utf8

    $text = ($output | Out-String)
    $hasSuccessMarker = $false
    foreach($marker in $SuccessMarkers){
        if($text -match [regex]::Escape($marker)){
            $hasSuccessMarker = $true
            break
        }
    }
    $passed = $hasSuccessMarker -and (-not ($text -match "\[FAIL\]|One or more test files failed|Arrow parsing gate failed"))

    $script:steps += [PSCustomObject]@{
        Name = $Name
        Passed = $passed
        Log = $LogPath
    }

    if($passed){
        Write-Host "PASS: $Name"
    }
    else{
        Write-Error "FAIL: $Name (see $LogPath)"
        throw "Gate step failed: $Name"
    }
}

try {
    Invoke-GateStep -Name "Live executeDaxQueries returns Arrow IPC" -Command {
        & $AssertArrowShape
    } -LogPath (Join-Path $ArtifactsDir ("{0}-00-arrow-shape.log" -f $stamp)) -SuccessMarkers @("PASS: executeDaxQueries still returns Apache Arrow IPC.")

    Invoke-GateStep -Name "DateDim parity focused" -Command {
        & $RunPQTests -Compile $true -TestFileName "PBIRESTAPIComm.tests.datasets.parity.query.pq"
    } -LogPath (Join-Path $ArtifactsDir ("{0}-01-parity.log" -f $stamp))

    Invoke-GateStep -Name "Connector proof" -Command {
        & $RunPQTests -Compile $false -TestFileName "PBIRESTAPIComm.tests.connector.proof.query.pq"
    } -LogPath (Join-Path $ArtifactsDir ("{0}-02-connector-proof.log" -f $stamp))

    Invoke-GateStep -Name "Arrow helper unit tests" -Command {
        & $RunPQTests -Compile $false -TestFileName "PBIRESTAPIComm.tests.arrow.helpers.query.pq"
    } -LogPath (Join-Path $ArtifactsDir ("{0}-03-arrow-helpers.log" -f $stamp))

    Invoke-GateStep -Name "Arrow static fixture parser" -Command {
        & $RunPQTests -Compile $false -TestFileName "PBIRESTAPIComm.tests.arrow.staticfixture.query.pq"
    } -LogPath (Join-Path $ArtifactsDir ("{0}-04-arrow-staticfixture.log" -f $stamp))

    Invoke-GateStep -Name "DateDim Arrow soak" -Command {
        & $RunSoak -Iterations $SoakIterations
    } -LogPath (Join-Path $ArtifactsDir ("{0}-05-soak.log" -f $stamp)) -SuccessMarkers @("All soak iterations passed")
}
catch {
    # continue to summary generation below
}

$allPassed = ($script:steps.Count -gt 0) -and ($script:steps | Where-Object { -not $_.Passed } | Measure-Object).Count -eq 0

$lines = @()
$lines += "# Arrow Parsing Gate"
$lines += ""
$lines += "Generated: $(Get-Date -Format s)"
$lines += ""
$lines += "| Step | Status | Log |"
$lines += "|---|---|---|"
foreach($s in $script:steps){
    $status = if($s.Passed) { "PASS" } else { "FAIL" }
    $lines += "| $($s.Name) | $status | $($s.Log) |"
}
$lines += ""
$lines += "Overall: $(if($allPassed){"PASS"} else {"FAIL"})"

$lines | Out-File -FilePath $summaryPath -Encoding utf8

Write-Host ""
Write-Host "Summary written: $summaryPath"

if($allPassed){
    Write-Host "Arrow parsing gate passed"
    exit 0
}

Write-Error "Arrow parsing gate failed. See $summaryPath"
exit 1
